server:
  port: 8083

spring:
  kafka:
    consumer:
      consumer-coffee:
        group-id: "grpid_coffee"
        topic: "coffee"
      bootstrap-servers: "127.0.0.1:9092"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 1
      session-timeout-ms: 115000
      properties-isolation-level: read_committed